# Your Solution
apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books-deployment
  template:
    metadata:
      labels:
        app: books-deployment
    spec:
      containers: 
      - name: books-deployment
        image: lyons72p.azurecr.io/books-deployment:1
        imagePullPolicy: Always
        env:
         - name: PORT
           value: "8000" 
---
apiVersion: v1
kind: Service
metadata:
  name: books-deployment
spec:
  selector:
    app: books-deployment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-deployment
  template:
    metadata:
      labels:
        app: inventory-deployment
    spec:
      containers:
      - name: inventory-deployment
        image: lyons72p.azurecr.io/inventory-deployment:1
        imagePullPolicy: Always
        env:
         - name: PORT
           value: "8001" 
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-deployment
spec:
  selector:
    app: inventory-deployment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001